version: "3.4"
name: "local-db-replication"

services:
  source_db:
    image: postgres:14-alpine
    container_name: "source_db"
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/.docker/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/pgdata
    restart: unless-stopped

  adminer:
    image: adminer:standalone
    ports:
      - "8080:8080"
    depends_on:
      - source_db
    restart: unless-stopped
