version: "3.4"
name: "db-replication"

services:
  source_db:
    image: postgres:14-alpine
    container_name: "source_db"
    ports:
      - "5432:5432"
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/pgdata
      - .docker/backups/postgres:/backups
      - .docker/postgres-add-de-user.sh:/docker-entrypoint-initdb.d/postgres-add-de-user.sh
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/pgdata
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer:standalone
    container_name: "adminer"
    ports:
      - "8080:8080"
    depends_on:
      - source_db
    restart: unless-stopped

  upstream-app:
    image: upstream-app:dev
    container_name: "upstream-app"
    ports:
      - "8501:8501"
    volumes:
      - ./app/app:/app
    env_file: .env
    restart: on-failure
    depends_on:
      - source_db
    healthcheck:
      test: curl --fail http://localhost:8501/healthz || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 10s

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    volumes:
      - .docker/data/zookeeper:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=0
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SYNC_LIMIT=7 # How far out of date a server can be from a leader
      - ZOO_LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - kafka_networks

  kafka-0:
    image: bitnami/kafka:3.5
    container_name: kafka-server
    ports:
      - "9092:9092"
    volumes:
      - .docker/data/kafka-0:/bitnami/kafka
      - .docker/log/kafka-0:/tmp/kafka_mounts/logs
    environment:
      - KAFKA_BROKER_ID=0
      - ALLOW_PLAINTEXT_LISTENER=true
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LOG_DIRS=/tmp/kafka_mounts/logs
    restart: unless-stopped
    depends_on:
      - zookeeper
    networks:
      - kafka_networks
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server kafka-server:9092 || exit -1
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s

  kafka-1:
    image: bitnami/kafka:3.5
    container_name: kafka-1
    ports:
      - ":9092"
    volumes:
      - .docker/data/kafka-1:/bitnami/kafka
      - .docker/log/kafka-1:/tmp/kafka_mounts/logs
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=true
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LOG_DIRS=/tmp/kafka_mounts/logs
    restart: unless-stopped
    depends_on:
      - zookeeper
    networks:
      - kafka_networks
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server kafka-1:9092 || exit -1
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s

  kafka-2:
    image: bitnami/kafka:3.5
    container_name: kafka-2
    ports:
      - ":9092"
    volumes:
      - .docker/data/kafka-2:/bitnami/kafka
      - .docker/log/kafka-2:/tmp/kafka_mounts/logs
    environment:
      - KAFKA_BROKER_ID=2
      - ALLOW_PLAINTEXT_LISTENER=true
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LOG_DIRS=/tmp/kafka_mounts/logs
    restart: unless-stopped
    depends_on:
      - zookeeper
    networks:
      - kafka_networks
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server kafka-2:9092 || exit -1
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.5.0.amd64
    container_name: kafka-connect
    ports:
      - "9092"
      - "8083:8083"
    env_file: .env
    restart: unless-stopped
    depends_on:
      - zookeeper
      - kafka-0
    networks:
      - kafka_networks
    healthcheck:
      test: curl http://localhost:8083 || exit -1
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-manager-ui
    ports:
      - "8000:8080"
    env_file: .env
    depends_on:
      - zookeeper
      - kafka-0
    networks:
      - kafka_networks

networks:
  kafka_networks:
    driver: bridge
