build:
	docker compose build

up:
	docker compose up

up-d:
	docker compose up -d

up-build:
	docker compose up --build

down:
	docker compose down

restart:
	docker compose down && docker compose up

restart-d:
	docker compose down && docker compose up -d
